var COIN_BITCOIN = 0;
var COIN_ETHEREUM = 1;
var COIN_THEDAO_ETHEREUM = 2;
var COIN_DASH = 3;
var COIN_ETHEREUM_CLASSIC = 4;
var COIN_AUGUR_ETHEREUM = 5;
var COIN_LITECOIN = 6;
var COIN_LISK = 7;
var COIN_ZCASH = 8;
var COIN_TESTNET_ROOTSTOCK = 9;
//@note@:@here:@zcash
//var COIN_NUMCOINTYPES = 9;
var COIN_NUMCOINTYPES = 10;

var COIN_UNITLARGE = 0;
var COIN_UNITSMALL = 1;
var COIN_NUMUNITTYPES = 2;